### ISSUE TITLE
Implement endless scroll in Recycler View of both top rated and popular TV shows Tab

### ISSUE THREAD

**Issue by amanjeetsingh150** [amanjeetsingh150/Televize#1]

**Comment by codeteo** [comment]
I'll give it a try @amanjeetsingh150 :100:

**Comment by amanjeetsingh150** [comment]
@codeteo sure you can go ahead :+1:

**Comment by aldocano** [comment]
Can i give it a try @amanjeetsingh150  ?

**Comment by amanjeetsingh150** [comment]
@aldocano the PR related to this issue is already opened and ready for review you can go through rest of my repos for any remaining opened issues

**Comment by aldocano** [comment]
@amanjeetsingh150  okay, thanks.

**Comment by amanjeetsingh150** [comment]
#2 the feature has been merged :+1:
